# Generated by Django 3.2.12 on 2022-03-14 07:33

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('hotel_name', models.CharField(max_length=20, verbose_name='酒店名称')),
                ('hotel_mian_img', models.ImageField(upload_to=app.models.user_directory_path, verbose_name='酒店主图')),
                ('decs', models.TextField(verbose_name='酒店简介')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='酒店地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to=app.models.Room, verbose_name='房间环境图')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='对应房间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=20, verbose_name='房型名称')),
                ('room_price', models.CharField(max_length=10, verbose_name='房型价格')),
                ('room_mian_img', models.ImageField(upload_to=app.models.user_directory_path, verbose_name='房型主图')),
                ('room_num', models.IntegerField(verbose_name='房间总数')),
                ('room_reservation', models.IntegerField(verbose_name='已预定数')),
                ('note', models.CharField(max_length=200, verbose_name='备注')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='对应酒店')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to=app.models.user_directory_path, verbose_name='酒店环境图')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='对应酒店')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
