# Generated by Django 3.2.12 on 2022-03-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=200, verbose_name='爬取网址')),
                ('data', models.CharField(max_length=20, verbose_name='爬取关键信息')),
                ('callback', models.CharField(max_length=20, verbose_name='回调｜备注')),
            ],
            options={
                'verbose_name': '爬虫',
                'verbose_name_plural': '爬虫',
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': '添加新的酒店', 'verbose_name_plural': '添加新的酒店'},
        ),
        migrations.AlterModelOptions(
            name='hotel_img',
            options={'verbose_name': '酒店图', 'verbose_name_plural': '酒店图'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '根据酒店添加新的房型', 'verbose_name_plural': '根据酒店添加新的房型'},
        ),
        migrations.AlterModelOptions(
            name='room_img',
            options={'verbose_name': '房型图', 'verbose_name_plural': '房型图'},
        ),
    ]
